version: '3.9'

services:
  palworld:
    image: ${REPOSITORY}:${VERSION}
    build:
      context: ..
      dockerfile: ${PALWORLD_DIRECTORY}/Dockerfile
      args:
        - SERVER_FILES=${SERVER_FILES}
        - PALWORLD_DIRECTORY=${PALWORLD_DIRECTORY}
    volumes:
      - type: volume
        source: PALWORLD_DATA
        target: /palworld/Pal/Saved/SaveGames
volumes:
  PALWORLD_DATA: